// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using LinqSharp.Test;

namespace LinqSharp.Test.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190912080758_201909120607")]
    partial class _201909120607
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("NLinq.Test.CompositeKeyModel", b =>
                {
                    b.Property<Guid>("Id1");

                    b.Property<Guid>("Id2");

                    b.HasKey("Id1", "Id2");

                    b.ToTable("CompositeKeyModels");
                });

            modelBuilder.Entity("NLinq.Test.EntityMonitorModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ProductName");

                    b.HasKey("Id");

                    b.ToTable("EntityMonitorModels");
                });

            modelBuilder.Entity("NLinq.Test.SimpleModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Age");

                    b.Property<DateTime>("Birthday");

                    b.Property<string>("NickName");

                    b.Property<string>("RealName");

                    b.HasKey("Id");

                    b.ToTable("SimpleModels");
                });

            modelBuilder.Entity("NLinq.Test.TrackModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Automatic");

                    b.Property<DateTime>("CreationTime");

                    b.Property<string>("ForCondensed");

                    b.Property<string>("ForLower");

                    b.Property<string>("ForTrim");

                    b.Property<string>("ForUpper");

                    b.Property<DateTime>("LastWriteTime");

                    b.HasKey("Id");

                    b.ToTable("TrackModels");
                });
#pragma warning restore 612, 618
        }
    }
}
